name: Print PR Diff

on: pull_request

permissions:
  contents: read

jobs:
  print_diff:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with all branches
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Get the PR diff in raw and JSON format
      - uses: GrantBirki/git-diff-action@vX.X.X
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: "true"  # Prevents console overflow
          base_branch: HEAD^1        # Compare PR merge commit to its first parent

      # Print the raw diff text
      - name: Print raw diff
        run: cat ${{ steps.git-diff-action.outputs.raw-diff-path }}
